apiVersion: v1
kind: Service
metadata:
  name: envoy
  labels:
    app: envoy
spec:
  clusterIP: None # headless service
  selector:
    app: envoy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
