apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

namespace: envoy-ingress

configMapGenerator:
- behavior: merge
  files:
  - configs/xds/cds.yaml
  - configs/xds/rds.yaml
  name: envoy-cfg-xds
  options:
    disableNameSuffixHash: true
